export const RELEVANT_STYLE_PROPS = [
  "color",
  "background-color",
  "background-image",
  "font-family",
  "font-size",
  "font-weight",
  "line-height",
  "letter-spacing",
  "margin",
  "padding",
  "border",
  "border-radius",
  "box-shadow",
  "opacity",
  "display",
  "flex-direction",
  "gap",
  "grid-template-columns",
  "transition",
  "transform",
] as const;
